<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="heros_wheel">		
<xacro:macro name="heros_wheel" params="front_rear left_right flip_y flip_z">

  <link name="wheel_${front_rear}_${left_right}">
    <collision>
      <origin xyz="0 0.115 0" rpy="${-PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>			
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://bresilla/meshes/wheel.STL" />
      </geometry>
      <material name="">
        <color rgba="0.25 0.25 0.25 1" />
      </material>
    </visual>			
    <inertial>
      <origin xyz="0 0.115 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.046" ixy="0" ixz="0" iyy="0.072" iyz="0" izz="0.045" />
    </inertial>		
  </link>
		
  <gazebo reference="wheel_${front_rear}_${left_right}">
    <gravity>true</gravity>
    <mu1>10</mu1>
    <mu2>10</mu2>
    <kd>1</kd>
    <kp>10000000000.0</kp>
    <fdir1>0 0 1</fdir1>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="joint_base_wheel_${front_rear}_${left_right}" type="continuous">
    <parent link="drive_box_${front_rear}"/>
    <child link="wheel_${front_rear}_${left_right}"/>
    <origin xyz="0.063 ${flip_y*flip_z * 0.162} -0.184" rpy="0 0 ${PI/2 - PI/2*flip_y*flip_z }"/>
    <axis xyz="0 ${flip_y * 1} 0" />
  </joint>
		
  <transmission name="trans_wheel_${front_rear}_${left_right}">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_base_wheel_${front_rear}_${left_right}">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_wheel_${front_rear}_${left_right}">
      <mechanicalReduction>100</mechanicalReduction>
    </actuator>
  </transmission>

</xacro:macro>
</robot>
